In [2]:
from transformers import AutoModel, AutoModelForSequenceClassification

- 加载模型
  - 加载远程模型
  - 加载本地模型
  - 加载带任务头的模型
- 前向传播
  - 原始模型的前向传播
  - 带任务头的前向传播

# 加载模型

## 加载远程模型

* 国内源更改：

  * Linux、MacOS：将 `export HF_ENDPOINT=https://hf-mirror.com` 添加到 `~/.bashrc` 或 `~/.zshrc` 文件中，然后 `source ~/.zshrc`

  * Windows：添加环境变量 `HF_ENDPOINT` 值为 `https://hf-mirror.com`

* 模型默认保存地址为：`~/.cache/huggingface/hub/`

In [4]:
model = AutoModel.from_pretrained("google-bert/bert-base-chinese")

config.json: 0.00B [00:00, ?B/s]

c:\Users\Refone\.conda\envs\nlp-learn\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Refone\.cache\huggingface\hub\models--google-bert--bert-base-chinese. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


model.safetensors:   0%|          | 0.00/412M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: google-bert/bert-base-chinese
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [5]:
print(model)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(21128, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

上面模型存放地址：
`C:\Users\Refone\.cache\huggingface\hub\models--google-bert--bert-base-chinese\snapshots\8f23c25b06e129b6c986331a13d8d025a92cf0ea`

## 加载本地模型

```
本地模型目录结构：
bert-base-chinese/
|-- config.json
|-- model.safetensors
|-- tokenizer.json
|-- tokenizer_config.json
|-- vocab.txt
```

In [6]:
path = 'D:/AI/hugging face/bert-base-chinese'
model = AutoModel.from_pretrained(path)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: D:/AI/hugging face/bert-base-chinese
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [7]:
print(model)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(21128, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

## 加载带任务头的模型

Transformer 架构模型 Docs：
- https://hf-mirror.com/docs/transformers/index
- https://huggingface.co/docs/transformers/index

In [8]:
# 下载过的同名模型就不会再下载了，直接从本地加载
model4sc = AutoModelForSequenceClassification.from_pretrained("google-bert/bert-base-chinese")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-chinese
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.seq_relationship.weight                | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
classifier.weight                          | MISSING    | 
classifier.bias                            | MISSING    | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


In [9]:
print(model)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(21128, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

In [ ]:
# 还可以指定分类数量
model4sc2 = AutoModelForSequenceClassification.from_pretrained(path, num_labels=5)

# 前向传播

In [14]:
import torch

vocab_size = 1000
N = 4
L = 6

input_ids = torch.randint(low=0, high=vocab_size, size=(N, L))
print(input_ids.shape, input_ids.dtype)
print(input_ids)

torch.Size([4, 6]) torch.int64
tensor([[929, 285, 929, 815, 678, 664],
        [875, 653, 665, 999, 528, 956],
        [216, 398, 214, 422, 378, 125],
        [ 10, 922, 680, 690, 441, 938]])


## 原始模型的前向传播

In [17]:
output = model(input_ids)
print(output)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.2508, -0.3489,  0.2318,  ...,  1.0539,  0.6682, -0.3673],
         [-0.4367, -0.6144,  0.3895,  ...,  0.8571,  0.5040, -0.2397],
         [-0.5340, -0.4908,  0.4214,  ...,  0.6976,  0.5925, -0.2973],
         [-0.3223, -0.4644,  0.2783,  ...,  0.9507,  0.3702, -0.1167],
         [-0.4737, -0.2966,  0.9234,  ...,  0.5182,  0.8239, -0.3763],
         [-0.3169, -0.1501,  0.0603,  ...,  1.5922,  0.4970, -0.4254]],

        [[-0.1424,  0.5827, -0.7838,  ...,  1.0455,  0.0808,  0.2248],
         [ 0.1698,  0.6658,  0.7885,  ...,  0.1671,  0.4999,  0.5022],
         [-0.0733,  0.4895,  0.9100,  ...,  0.0895,  0.3262,  0.5408],
         [ 0.3324,  0.5084,  1.2988,  ...,  0.1464,  0.1858,  0.5217],
         [ 0.3753,  0.2919,  0.9362,  ...,  0.1212, -0.1382,  0.4848],
         [ 0.3484,  0.5052,  0.7460,  ..., -0.0710, -0.5079,  0.5304]],

        [[ 0.1890, -0.0263,  0.8840,  ...,  0.5187, -1.0331,  0.5978],
         [

In [18]:
print(output.last_hidden_state.shape)
print(output.pooler_output.shape)

torch.Size([4, 6, 768])
torch.Size([4, 768])


## 带任务头的模型

In [22]:
output = model4sc2(input_ids)   # 5 分类模型，输入 (N, L)，输出 (N, 5)
print(output.logits.shape)  # (N, 5)
print(output)

torch.Size([4, 5])
SequenceClassifierOutput(loss=None, logits=tensor([[-0.0773,  0.2017,  0.3474, -0.2779,  0.3005],
        [ 0.0859, -0.6243,  0.3011, -0.3531,  0.4925],
        [ 0.1023, -0.1126,  0.2411, -0.3832,  0.0269],
        [ 0.0473, -0.2347,  0.1725,  0.0601,  0.4124]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


In [23]:
# 定义目标值
targets = torch.randint(low=0, high=5, size=(N,))
print(targets)

tensor([3, 2, 3, 0])


In [24]:
output = model4sc2(input_ids, labels=targets)
output.loss.backward()  # 反向传播计算梯度
print(output.logits)  # (N, 5)
print(output.loss)  # 输出损失值

tensor([[-0.0773,  0.2017,  0.3474, -0.2779,  0.3005],
        [ 0.0859, -0.6243,  0.3011, -0.3531,  0.4925],
        [ 0.1023, -0.1126,  0.2411, -0.3832,  0.0269],
        [ 0.0473, -0.2347,  0.1725,  0.0601,  0.4124]],
       grad_fn=<AddmmBackward0>)
tensor(1.7619, grad_fn=<NllLossBackward0>)
